on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotenvs:
          # latest k8s version test with various options
          - |
            K8S_VERSION=1.35
            DATACENTER_ID=US-NY2
            HIGH_AVAILABILITY=yes
          - |
            K8S_VERSION=1.35
            DATACENTER_ID=EU
            HIGH_AVAILABILITY=no
          - |
            K8S_VERSION=1.35
            DATACENTER_ID=IL
            HIGH_AVAILABILITY=no
            WITH_BASTION=no
          - |
            K8S_VERSION=1.35
            DATACENTER_ID=US-NY2
            HIGH_AVAILABILITY=yes
          - |
            K8S_VERSION=1.35
            DATACENTER_ID=US-NY2
            HIGH_AVAILABILITY=yes
          # older k8s version with same options
          - |
            K8S_VERSION=1.34
            DATACENTER_ID=EU
            HIGH_AVAILABILITY=yes
#          - |
#            K8S_VERSION=1.33
#            DATACENTER_ID=IL
#            HIGH_AVAILABILITY=yes
#          - |
#            K8S_VERSION=1.32
#            DATACENTER_ID=US-NY2
#            HIGH_AVAILABILITY=yes
      fail-fast: false  # must continue all tests for cleanup
    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v3
      - run: |
          wget https://cloudcli.cloudwm.com/binaries/latest/cloudcli-linux-amd64.tar.gz
          tar -xvf cloudcli-linux-amd64.tar.gz
          chmod +x cloudcli
          sudo mv cloudcli /usr/local/bin/cloudcli
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KAMATERA_SSHKEY_PUB }}" > ~/.ssh/id_rsa.pub
          echo "${{ secrets.KAMATERA_SSHKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - uses: astral-sh/setup-uv@v7
        with:
          working-directory: tests
      - env:
          KAMATERA_API_CLIENT_ID: ${{ secrets.KAMATERA_API_CLIENT_ID }}
          KAMATERA_API_SECRET: ${{ secrets.KAMATERA_API_SECRET }}
        run: |
          cd tests
          echo "${{ matrix.dotenvs }}" > .env
          uv sync
          uv run python -u -m pytest -vvx --capture=tee-sys tests
