on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DATACENTER_ID: ["US-NY2", "EU", "IL"]
        K8S_VERSION: ["1.35", "1.34", "1.33", "1.32"]
        HIGH_AVAILABILITY: ["yes", "no"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v3
      - run: |
          wget https://cloudcli.cloudwm.com/binaries/latest/cloudcli-linux-amd64.tar.gz
          tar -xvf cloudcli-linux-amd64.tar.gz
          chmod +x cloudcli
          sudo mv cloudcli /usr/local/bin/cloudcli
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KAMATERA_SSHKEY_PUB }}" > ~/.ssh/id_rsa.pub
          echo "${{ secrets.KAMATERA_SSHKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - uses: astral-sh/setup-uv@v7
        with:
          working-directory: tests
      - env:
          KAMATERA_API_CLIENT_ID: ${{ secrets.KAMATERA_API_CLIENT_ID }}
          KAMATERA_API_SECRET: ${{ secrets.KAMATERA_API_SECRET }}
          DATACENTER_ID: ${{ matrix.DATACENTER_ID }}
          K8S_VERSION: ${{ matrix.K8S_VERSION }}
          HIGH_AVAILABILITY: ${{ matrix.HIGH_AVAILABILITY }}
        run: |
          cd tests
          uv sync
          uv run python -u -m pytest -vvx --capture=tee-sys tests
